## @file
# config.plist configuration file patches for running macOS on Hyper-V
#
# Copyright (c) 2021-2025, Goldfish64. All rights reserved.
# Copyright (c) 2023-2025, Cory Bennett. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
##

# This file builds on the existing defaults from OCE-Build and MacHyperVSupport.
# @see https://github.com/Qonfused/OCE-Build/blob/main/docs/resources/base-config.yml
# @see https://github.com/acidanthera/MacHyperVSupport/blob/master/README.md

# Refer to the below resources for more information on sensible defaults:
# - https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf
#   (or https://dortania.github.io/docs/latest/Configuration.html)

#region: Base Configuration - Keep in sync with docs/resources/base-config.yml

################################################################################
#                             Misc. Cosmetic fixes                             #
################################################################################

# Remove warning comments
@delete('#WARNING - 1', '#WARNING - 2', '#WARNING - 3', '#WARNING - 4')
# Remove redundant comment
@delete('NVRAM.Add.7C436110-AB2A-4BBB-A880-FE41995C9F82.#INFO (prev-lang:kbd)')

Misc:
  Boot:
    HideAuxiliary:                    Boolean | false

# Changes default macOS installer/keyboard language to English.
# - You can find a list of supported languages below (convert HEX -> ASCI):
#   https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/AppleKeyboardLayouts/AppleKeyboardLayouts.txt
NVRAM:
  Add:
    7C436110-AB2A-4BBB-A880-FE41995C9F82:
      prev-lang:kbd:                  Data  | <>

################################################################################

@ifdef(RELEASE)
# Use default GoldenGate theme with OpenCanopy.
# - https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html
Misc:
  Boot:
    PickerMode:                       String  | "External"
    PickerVariant:                    String  | "Acidanthera\GoldenGate"
@endif

################################################################################
#                           Platform (SMBIOS) fixes                            #
################################################################################

PlatformInfo:
  Generic:
    SystemProductName:     String  | "MacBookPro16,1"
    SystemSerialNumber:    String  | "C02DX0L2MD6N"
    MLB:                   String  | "C020531024NN9PRA8"
    SystemUUID:            String  | "95E328F8-EFBF-4C3D-A706-7DB2456595FF"
    ROM:                   Data    | <0016cb001122>

################################################################################

@ifdef(DEBUG)
# Debugging quirks (recommended with DEBUG version of OpenCore)
# - https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html
# - https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/kernel-debugging.html#nvram
Kernel:
  Quirks:
    PanicNoKextDump:                  Boolean | true
    PowerTimeoutKernelPanic:          Boolean | true
Misc:
  Debug:
    AppleDebug:                       Boolean | true
    ApplePanic:                       Boolean | true
    DisableWatchDog:                  Boolean | true
    Target:                           Number  | 67
NVRAM:
  Add:
    7C436110-AB2A-4BBB-A880-FE41995C9F82:
      # Breakdown of used boot args:
      # `-v`              (verbose mode)
      # `debug=0x100`     (debug mask; disables watchdog to avoid panic reboot)
      # `keepsyms=1`      (show panic log debug symbols)
      # `msgbuf=1048576`  (Resizes kernel msg buffer to 1 MB; avoids truncation)
      bluetoothExternalDongleFailed:   Data    | <00>
      bluetoothInternalControllerInfo: Data    | <000000000000000089653A552EFD>
      boot-args:                       String  | "-v debug=0x100 keepsyms=1 msgbuf=1048576 agdpmod=vit9696"
@endif


@ifdef(RELEASE)
NVRAM:
  Add:
    7C436110-AB2A-4BBB-A880-FE41995C9F82:
      boot-args:                      String  | "agdpmod=vit9696"
@endif

################################################################################
#                            Cosmetic Plist Fixes                              #
################################################################################

# Clear default entries from Sample.plist
ACPI:
  @override
  Delete:                             Array   | []
Booter:
  @override
  MmioWhitelist:                      Array   | []
  @override
  Patch:                              Array   | []
Kernel:
  @override
  Block:                              Array   | []
  @override
  Force:                              Array   | []
  @override
  Patch:                              Array   | []
Misc:
  @override
  Entries:                            Array   | []
UEFI:
  @override
  ReservedMemory:                     Array   | []

#endregion

################################################################################
#                               ACPI related fixes                             #
################################################################################

ACPI:
  @override
  Patch:
    - Comment:              String  | "PNLF to XNLF Rename"
      Count:                Number  | 0
      Find:                 Data    | <504E4C46>
      Replace:              Data    | <584E4C46>
    - Comment:              String  | "_OSI to XOSI"
      Count:                Number  | 0
      Find:                 Data    | <5F4F5349>
      Replace:              Data    | <584F5349>

################################################################################
#                                  Boot fixes                                  #
################################################################################

UEFI:
  APFS:
    # Disables minimum APFS version for macOS Catalina and earlier boot entries.
    MinDate:                Number  | -1
    MinVersion:             Number  | -1
  Output:
    # Sets proper display scaling for boot picker + debug logging.
    UIScale:                Number  | -1

################################################################################
#                             Security related fixes                           #
################################################################################

Misc:
  Security:
    # Allows setting a default boot entries when holding the CTRL key.
    AllowSetDefault:        Boolean | true
    # Allows all bootable parition types to show in the boot picker.
    # - https://dortania.github.io/OpenCore-Post-Install/universal/security/scanpolicy.html
    ScanPolicy:             Number  | 0
    # Apple Secure Boot hardware model and policy
    # - Possible values include:
    #   - Disabled: No model, Secure Boot will be disabled.
    #   - Default: Currently set to x86legacy
    # - @see https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#securebootmodel
    SecureBootModel:        String  | "Disabled"
    # OpenCore vaulting configuration (optional=no vault enforced, insecure)
    # - @see https://dortania.github.io/OpenCore-Post-Install/universal/security/vault.html
    Vault:                  String  | "Optional"
NVRAM:
  Add:
    7C436110-AB2A-4BBB-A880-FE41995C9F82:
      # Enables System Integrity Protection (SIP) setting in macOS.
      #
      # By default, we disable kext signing (0x1) for MacHyperVFramebuffer;
      # required for macOS 11 (Big Sur) and newer.
      #
      # - Possible values include:
      #   - 00000000: Default (enabled)
      #   - 01000000: Disables Kext signing
      #   - 02000000: Disables filesystem protections
      #   - 03000000: Disables both Kext signing and filesystem protections
      #   - 67000000: Disables all SIP protections
      #   - FF030000: Disables all flags in macOS High Sierra
      #   - FF070000: Disables all flags in macOS Mojave and macOS Catalina
      #   - FF0F0000: Disables all flags in macOS Big Sur
      # - @see https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#disabling-sip
      csr-active-config:    Data    | <00000000>
NVRAM:
  Delete:
    7C436110-AB2A-4BBB-A880-FE41995C9F82:
      # Overrides the default SIP setting in macOS.
      - csr-active-config

################################################################################
#                             iGPU Framebuffer Patch                           #
################################################################################

DeviceProperties:
  @override
  Add:
    PciRoot(0x0)/Pci(0x2,0x0):
      AAPL,GfxYTile:                  Data    | <01000000>
      AAPL,ig-platform-id:            Data    | <00009B3E>
      device-id:                      Data    | <9B3E0000>
      enable-lspcon-support:          Data    | <01000000>
      framebuffer-con1-alldata:       Data    | <01010900 00080000 C7010000 02060A00 00040000 C7010000>
      framebuffer-con1-enable:        Data    | <01000000>
      framebuffer-con1-has-lspcon:    Data    | <01000000>
      framebuffer-fbmem:              Data    | <00009000>
      framebuffer-patch-enable:       Data    | <01000000>
      framebuffer-stolenmem:          Data    | <00003001>
      framebuffer-unifiedmem:         Data    | <00000080>
      hda-gfx:                        String  | "onboard-1"
      model:                          String  | "Intel UHD Graphics 620"

################################################################################
#                      Optional BIOS/firmware related fixes                    #
################################################################################

#Scenario 1:
#Booter:
#  Quirks:
#    DevirtualiseMmio:                 Boolean | true
#    ProtectUefiServices:              Boolean | true
#    SyncRuntimePermissions:           Boolean | true
#
#Kernel:
#  Quirks:
#    AppleXcpmCfgLock:                 Boolean | true
#    DisableIoMapper:                  Boolean | true
#
#UEFI:
#  Quirks:
#    ReleaseUsbOwnership:              Boolean | true

#Scenario 2:
Booter:
  Quirks:
    ProtectUefiServices:              Boolean | true
    SetupVirtualMap:                  Boolean | false

Kernel:
  Quirks:
    AppleXcpmCfgLock:                 Boolean | true
    DisableIoMapper:                  Boolean | true

ACPI:
  Quirks:
    ResetLogoStatus:                  Boolean | false
