name: Build OpenCore

on:
  workflow_dispatch:
      inputs:
        edition:
         required: true
         type: choice
         description: Select edition
         options:
         - DEBUG
         - RELEASE
         default: DEBUG
        serialdata:
         required: true
         description: Custom .serialdata file path
         default: https://raw.githubusercontent.com/Niktendo/Medion-S17404-Hackintosh-OpenCore/refs/heads/main/src/.serialdata.example

env:
  version: 1.0

jobs:
  Build-OpenCore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

#      - name: Get additional packages
#        run: |
#          if [ -n "${{ github.event.inputs.packages }}" ]; then
#          wget -P ${{ github.workspace }} ${{ github.event.inputs.packages }}
#          fi

      - name: Build
        run: |
          mv src/build-${{ inputs.edition }}.yml src/build.yml
          wget -O src/.serialdata ${{ inputs.serialdata }}
          wget -O src/bootstrap.sh https://raw.githubusercontent.com/Qonfused/OCE-Build/refs/heads/main/ci/bootstrap.sh
          bash src/bootstrap.sh build -c ${{ github.workspace }} -p config.yml
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: EFI
          path: ${{ github.workspace }}/dist/EFI
