# This is a basic workflow to help you get started with Actions

name: Build OpenCore Sequoia

# Controls when the workflow will run
on:
  workflow_dispatch:
      inputs:
        packages:
          description: "URLs to additional files to be included"
          required: false

jobs:
  Build-OpenCore-sequoia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

#      - name: Get additional packages
#        run: |
#          if [ -n "${{ github.event.inputs.packages }}" ]; then
#          wget -P ${{ github.workspace }} ${{ github.event.inputs.packages }}
#          fi

      - name: Build
        run: |
          cd src
          wget -O bootstrap.sh https://raw.githubusercontent.com/Qonfused/OCE-Build/refs/heads/main/ci/bootstrap.sh
          bash bootstrap.sh build -c ${{ github.workspace }} -p config.yml
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: 
          path: ${{ github.workspace }}/dist/
